---
- hosts: jenkins_slaves

  vars:
    - key_src: "/home/catroid/.ssh/id_rsa.pub"

  tasks:
    - name: Transfer master's public ssh-key to the slaves.
      authorized_key:
        user: catroid
        state: present
        key: "{{ lookup('file', key_src) }}"


- hosts: emulators
  become: yes

  tasks:
    - name: Enable multiarch.
      command: dpkg --add-architecture i386

    - name: Install Android SDK dependencies and other required packages.
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - "libstdc++6:i386"
        - "libgcc1:i386"
        - "zlib1g:i386"
        - "libncurses5:i386"
        - git
